version: "3.8"
services:
  postgis:
    image: postgis/postgis:15-3.3
    container_name: postgis
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: vessels
    ports:
      - "5432:5432"
    volumes:
      - postgis-data:/var/lib/postgresql/data

volumes:
  postgis-data:
